#!/usr/bin/env python
"""Prepare Fig. 6 endpoint-null controls from the reviewer-grade greedy run.

The endpoint null uses mutation-count-matched random endpoints generated by
the original reviewer-grade run. It tests whether the final target/CAGE gains
can be explained by mutation burden under the same sequence constraints.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import numpy as np
import pandas as pd


MODULE_ROOT = Path(__file__).resolve().parents[1]
DATA_RAW = MODULE_ROOT / "data" / "raw"
DATA_PROCESSED = MODULE_ROOT / "data" / "processed"
LOG_DIR = MODULE_ROOT / "logs"
RUN_LABEL = "reviewer_greedy_20260724_115905"


def find_run_root() -> Path:
    candidates = sorted(
        Path("G:/").glob(
            f"*/DeepEpromote/Drosophila/DeepSTARR/promoter_mut/results_context_dependent/reviewer_grade_runs/{RUN_LABEL}"
        )
    )
    if len(candidates) != 1:
        raise FileNotFoundError(f"Expected one {RUN_LABEL} run on G:, found {candidates}")
    return candidates[0]


def atomic_write_tsv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    df.to_csv(tmp, sep="\t", index=False)
    tmp.replace(path)


def read_endpoint_null(endpoint_dir: Path) -> pd.DataFrame:
    files = sorted(endpoint_dir.rglob("endpoint_null__*.tsv"))
    if len(files) != 830:
        raise RuntimeError(f"Expected 830 endpoint-null files, found {len(files)} in {endpoint_dir}")
    frames = []
    for path in files:
        df = pd.read_csv(path, sep="\t")
        df["source_file"] = path.name
        frames.append(df)
    out = pd.concat(frames, ignore_index=True)
    if len(out) != 16600:
        raise RuntimeError(f"Expected 16,600 endpoint-null rows, found {len(out)}")
    return out


def target_score(row: pd.Series) -> float:
    return float(row["Hk_pred"] if row["task"] == "HK" else row["Dev_pred"])


def main() -> None:
    DATA_RAW.mkdir(parents=True, exist_ok=True)
    DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    run_root = find_run_root()
    endpoint_dir = run_root / "checkpoints" / "endpoint_null"
    primary_src = run_root / "summaries" / "primary_greedy_summary.tsv"
    endpoint = read_endpoint_null(endpoint_dir)
    primary = pd.read_csv(primary_src, sep="\t")

    # Keep the frozen package compact: one concatenated raw table plus summaries.
    endpoint_raw = DATA_RAW / "endpoint_null_mutation_count_matched.tsv"
    atomic_write_tsv(endpoint, endpoint_raw)
    shutil.copy2(primary_src, DATA_RAW / primary_src.name)

    primary_ref = primary[
        [
            "task",
            "ID",
            "init_score",
            "best_score",
            "init_cage",
            "best_cage",
            "delta_cage_at_best",
            "best_total_muts",
            "best_max_10bp_muts",
            "best_gc_delta",
            "reached_hit6",
        ]
    ].rename(
        columns={
            "init_score": "primary_init_target",
            "best_score": "primary_best_target",
            "init_cage": "primary_init_cage",
            "best_cage": "primary_best_cage",
            "reached_hit6": "primary_reached_hit6",
        }
    )
    merged = endpoint.merge(primary_ref, on=["task", "ID"], how="left", validate="many_to_one")
    if merged["primary_init_target"].isna().any():
        missing = int(merged["primary_init_target"].isna().sum())
        raise RuntimeError(f"Endpoint-null rows missing primary match: {missing}")

    merged["null_target_pred"] = merged.apply(target_score, axis=1)
    merged["null_target_delta_vs_init"] = merged["null_target_pred"] - merged["primary_init_target"]
    merged["null_cage_delta_vs_init"] = merged["CAGE_pred"] - merged["primary_init_cage"]
    merged["primary_target_delta_vs_init"] = merged["primary_best_target"] - merged["primary_init_target"]
    merged["primary_cage_delta_vs_init"] = merged["primary_best_cage"] - merged["primary_init_cage"]
    detail_cols = [
        "method",
        "task",
        "ID",
        "replicate",
        "matched_mutations",
        "attempts",
        "matched_success",
        "reached_hit6",
        "null_target_pred",
        "null_target_delta_vs_init",
        "CAGE_pred",
        "null_cage_delta_vs_init",
        "total_muts",
        "max_10bp_muts",
        "gc_delta",
        "primary_init_target",
        "primary_best_target",
        "primary_target_delta_vs_init",
        "primary_init_cage",
        "primary_best_cage",
        "primary_cage_delta_vs_init",
        "best_total_muts",
        "best_max_10bp_muts",
        "best_gc_delta",
        "source_file",
    ]
    detail = merged[detail_cols].copy()
    atomic_write_tsv(detail, DATA_PROCESSED / "endpoint_null_mutation_count_matched_detail.tsv")

    rows = []
    for task, sub in detail.groupby("task", sort=True):
        primary_task = primary[primary["task"] == task]
        rows.append(
            {
                "task": task,
                "null_rows": len(sub),
                "null_ids": sub["ID"].nunique(),
                "null_replicates_per_id": len(sub) / sub["ID"].nunique(),
                "null_hit6_rate": sub["reached_hit6"].astype(bool).mean(),
                "null_target_delta_median": sub["null_target_delta_vs_init"].median(),
                "null_target_delta_q95": sub["null_target_delta_vs_init"].quantile(0.95),
                "null_cage_delta_median": sub["null_cage_delta_vs_init"].median(),
                "null_cage_delta_q95": sub["null_cage_delta_vs_init"].quantile(0.95),
                "primary_ids": len(primary_task),
                "primary_hit6_rate": primary_task["reached_hit6"].astype(bool).mean(),
                "primary_target_delta_median": (primary_task["best_score"] - primary_task["init_score"]).median(),
                "primary_cage_delta_median": primary_task["delta_cage_at_best"].median(),
                "primary_total_muts_median": primary_task["best_total_muts"].median(),
                "null_total_muts_median": sub["total_muts"].median(),
            }
        )
    summary = pd.DataFrame(rows)
    atomic_write_tsv(summary, DATA_PROCESSED / "endpoint_null_mutation_count_matched_summary.tsv")

    manifest = pd.DataFrame(
        [
            {
                "run_label": RUN_LABEL,
                "source_endpoint_dir": str(endpoint_dir),
                "source_primary_summary": str(primary_src),
                "raw_concatenated_table": str(endpoint_raw),
                "detail_table": str(DATA_PROCESSED / "endpoint_null_mutation_count_matched_detail.tsv"),
                "summary_table": str(DATA_PROCESSED / "endpoint_null_mutation_count_matched_summary.tsv"),
                "n_endpoint_files": len(sorted(endpoint_dir.rglob("endpoint_null__*.tsv"))),
                "n_endpoint_rows": len(endpoint),
            }
        ]
    )
    manifest.to_csv(LOG_DIR / "endpoint_null_manifest.csv", index=False)
    print(f"Wrote endpoint-null control tables to {DATA_PROCESSED}")


if __name__ == "__main__":
    main()
